name: Dependency Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 0'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Safety and pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install "safety<2" pip-audit

      - name: Install project dependencies
        run: pip install -r backend/requirements.txt

      - name: Run Safety check (legacy, no login)
        run: safety check -r backend/requirements.txt

      - name: Run pip-audit scan
        run: pip-audit -r backend/requirements.txt
