name: Seguridad SAST con Bandit y Semgrep

on: [push, pull_request]

jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias SAST
        run: |
          pip install bandit semgrep

      - name: Ejecutar Bandit (backend)
        run: |
          bandit -r backend/ -f txt -o bandit_resultados.txt || true

      - name: Ejecutar Semgrep (backend y frontend)
        run: |
          semgrep scan \
            --config "p/owasp-top-ten" \
            --include 'backend/**/*.py' \
            --include 'frontend/**/*.[jt]s' \
            --include 'frontend/**/*.[jt]sx' \
            --include 'frontend/Dockerfile' \
            --include 'backend/Dockerfile' \
            -o semgrep_resultados.txt

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: resultados-sast
          path: |
            bandit_resultados.txt
            semgrep_resultados.txt

