name: Seguridad SAST con Bandit y Semgrep

on: [push, pull_request]

jobs:
  seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias SAST
        run: |
          pip install bandit semgrep

      - name: Ejecutar Bandit y guardar resultados
        run: bandit -r farmacia.py -f txt -o bandit_resultados.txt

      - name: Ejecutar Semgrep y guardar resultados
        run: semgrep scan --config "p/owasp-top-ten" -o semgrep_resultados.txt --output-format=text

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: resultados-sast
          path: |
            bandit_resultados.txt
            semgrep_resultados.txt

