name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit and Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install bandit semgrep

      - name: Run Bandit security scan
        run: bandit -r . --fail-under 5

      - name: Run Semgrep security scan
        run: semgrep --config=p/ci --fail-on-error
